---         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decbinhexconverter-deployment
  labels:
    app: decbinhexconverter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decbinhexconverter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: decbinhexconverter
    spec:
      containers:
      - name: decbinhexconverter
        image: stoleyourburger/decbinhexconverter:1.0.1
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: converter-service
spec:
 type: NodePort
 selector:   
  app: decbinhexconverter
 ports: 
 - port: 8080
   targetPort: 8080
   nodePort: 30080