name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    

    steps:
#    - uses: actions/checkout@v4
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag stoleyourburger/decbinhexconverter:$(date +%s)

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: stoleyourburger/decbinhexconverter:latest
        
    - name: Apply Kubernetes deployment manifest
      run: kubectl apply -f /root/actions-runner/_work/DecBinHexConverter/DecBinHexConverter/kubernetes/manifest.yml