name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    
    steps:

    - name: check repository
      uses: actions/checkout@v4

    - name: Log into Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: stoleyourburger/decbinhexconverter:1.0.1
        
    - name: Apply Kubernetes deployment manifest
      run: kubectl apply -f k8s/manifest.yml
